### ISSUE TITLE
Migration to Detox 19

### ISSUE THREAD

**Issue by d4vidi** [ouihealth/detox-puppeteer#12]
Hi,

we're [in-the-works](https://github.com/wix/Detox/pull/2980) for introducing some breaking changes to our external drivers support. It's mostly about moving code around -- not changing the functionality altogether (perhaps only light modifications).

I'd like to future-fix this project such that it would work out of the box when the changes are introduced. Question is - is there an execution platform through which this driver can be tested?

Thanks in advance.

---

@awinograd

**Comment by awinograd** [comment]
Hi @d4vidi.  I currently use my work's private repo using `yarn link` as the testing suite... 

That said, I just pushed https://github.com/ouihealth/detox-puppeteer/commit/200ea2a8de173753d296d1e53392e2dd56a4d884 which adds a test script to at least test the driver can spin up and run a basic assertion. Hopefully that's sufficient for your needs.

Thanks for helping keep this package compatible with detox!
