### ISSUE TITLE
Loading stripe.js makes detox-puppeteer hang indefinitely

### ISSUE THREAD

**Issue by philiplindberg** [ouihealth/detox-puppeteer#19]
I'm using stripe.js to handle payments in my react native expo app, but I've noticed that this library makes detox-puppeteer hang indefinitely after chromium is launched. 

I've tried using detox's `detoxURLBlacklistRegex` launch args to blacklist stripe, but can't seem to get the regex right. Any insight would be really appreciated.

Here's a repro of a simple expo app with stripe being loaded:
https://github.com/philiplindberg/detox-puppeteer-repro

**Comment by awinograd** [comment]
@philiplindberg thanks for filing the issue with a repro. I'll take a look at get back to you

**Comment by philiplindberg** [comment]
@awinograd Thanks for looking at that so quickly, 5.0.1 resolves the issue for me too.
