### ISSUE TITLE
Targeting Stripe Elements card fields on web

### ISSUE THREAD

**Issue by philiplindberg** [ouihealth/detox-puppeteer#20]
I'm using stripe.js to handle payments in my react native expo app, but I'm not sure how to target the Stripe Elements card fields for my detox tests on web. Here's a repro that hopefully demonstrates the issue:

https://github.com/philiplindberg/detox-puppeteer-stripe-repro

In `client/e2e/stripe.test.ts`, you'll see that I'm trying to target the Stripe Elements card number field by its label, which doesn't work on web. So my question is, which detox matcher(s) can I use to target the different stripe card fields?

To run the repro:
```sh
git clone https://github.com/philiplindberg/detox-puppeteer-stripe-repro
cd detox-puppeteer-stripe-repro

cd server
yarn install
yarn dev

# in another terminal window
cd client
yarn install
yarn start

# in another terminal window
cd client
yarn detox test -c web
```

**Comment by awinograd** [comment]
https://github.com/ouihealth/detox-puppeteer#workarounds getPuppeteerPage is probably what you're looking for. It jsut gives you the raw puppeteer page instance so you can use their full api

**Comment by philiplindberg** [comment]
Thanks for pointing me in the right direction @awinograd, must have missed that method in the docs.

For anyone else who wants to run e2e tests on a Stripe Elements form, here's the code I used to target the card fields:

```ts
const browser: Browser = (detox.device as any).deviceDriver.getBrowser()
const page = (await browser.pages())[0]

let cardInput: ElementHandle<Element> | null = null
let expiryInput: ElementHandle<Element> | null = null
let cvcInput: ElementHandle<Element> | null = null

for (const frame of page.frames()) {
  if (await frame.$('#Field-numberInput')) cardInput = await frame.$('#Field-numberInput')
  if (await frame.$('#Field-expiryInput')) expiryInput = await frame.$('#Field-expiryInput')
  if (await frame.$('#Field-cvcInput')) cvcInput = await frame.$('#Field-cvcInput')
}

await cardInput?.type('4242424242424242', { delay: 50 })
await expiryInput?.type('12/25', { delay: 50 })
await cvcInput?.type('123', { delay: 50 })
```

There's probably a simpler way to query for the individual card fields, but the above should at least work. The delay is just there to make it easier to visually debug the test.
